nginx:
  image: nginx:stable-alpine
  restart: always
  ports:
    - "80:80"
  volumes:
    - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
  links:
    - api-server
    - app-web
    - app-admin
    - app-desktop

api-server:
  image: 847166803921.dkr.ecr.us-east-1.amazonaws.com/staff-api-server:latest
  links:
   - mongo
   - rabbitmq
  environment:
   PORT: 3000
   MONGO_URI: mongodb://mongo/staffdotcom'
   RABBIT_URI: amqp://rabbitmq
   API_URL: "http://api.staff.local"
   NODE_ENV: production

app-web:
  image: 847166803921.dkr.ecr.us-east-1.amazonaws.com/staff-app-web:latest
  environment:
   PORT: 3000
   API_URL: "http://api.staff.local"
   NODE_ENV: production

app-admin:
  image: 847166803921.dkr.ecr.us-east-1.amazonaws.com/staff-app-admin:latest
  environment:
   PORT: 3000
   API_URL: "http://api.staff.local"
   NODE_ENV: production

app-desktop:
  image: 847166803921.dkr.ecr.us-east-1.amazonaws.com/staff-app-desktop:latest
  environment:
   PORT: 3000
   API_URL: "http://api.staff.local"
   NODE_ENV: production

mongo:
  image: mongo
  volumes:
    - ./storage/mongodb:/data/db

rabbitmq:
  image: rabbitmq

cadvisor:
  image: google/cadvisor
  #ports:
  #  - "8080:8080"
  expose:
    - "8080"
  volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw 
    - /sys:/sys:ro 
    - /var/lib/docker/:/var/lib/docker:ro

node-exporter:
  image: prom/node-exporter
  expose:
    - "9100"

prometheus:
  image: "prom/prometheus"
  links:
    - cadvisor
    - node-exporter
  ports:
    - "9090:9090"
  expose:
    - "9090"
  volumes:
    - ./etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

#sqlite3:
#  image: "prom/promdash"
#  command:
#    - "./bin/rake db:migrate"
#  volumes:
#    - "/tmp/prom:/tmp/prom"
#  environment:
#    - "DATABASE_URL=sqlite3:/tmp/prom/file.sqlite3"

grafana:
  image: "localhost:5000/mystaff-grafana"
  ports:
    - "3000:3000"
  expose:
    - "3000"
  volumes:
    - ./storage/grafana:/var/lib/grafana
    - ./etc/grafana/grafana.ini:/etc/grafana/grafana.ini

#promdash:
#  image: "prom/promdash"
#  ports:
#    - "3000:3000"
#  expose:
#    - "3000"
#  volumes:
#    - /tmp/prom:/tmp/prom
#  environment:
#    - "DATABASE_URL=sqlite3:/tmp/prom/file.sqlite3"
#  labels: 
#    - "name=prom dashboard"
#    - "description=Dashboards for metrics"
#    - "version=latest"

