nginx:
  image: nginx:stable-alpine
  restart: always
  ports:
    - "80:80"
  volumes:
    - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
  links:
    - api-server
    - app-web
    - app-admin
    - app-desktop

api-server:
  image: 847166803921.dkr.ecr.us-east-1.amazonaws.com/staff-api-server:latest
  links:
   - mongo
   - rabbitmq
  environment:
   PORT: 3000
   MONGO_URI: mongodb://mongo/staffdotcom'
   RABBIT_URI: amqp://rabbitmq
   API_URL: "http://api.staff.local"
   NODE_ENV: production

app-web:
  image: 847166803921.dkr.ecr.us-east-1.amazonaws.com/staff-app-web:latest
  environment:
   PORT: 3000
   API_URL: "http://api.staff.local"
   NODE_ENV: production

app-admin:
  image: 847166803921.dkr.ecr.us-east-1.amazonaws.com/staff-app-admin:latest
  environment:
   PORT: 3000
   API_URL: "http://api.staff.local"
   NODE_ENV: production

app-desktop:
  image: 847166803921.dkr.ecr.us-east-1.amazonaws.com/staff-app-desktop:latest
  environment:
   PORT: 3000
   API_URL: "http://api.staff.local"
   NODE_ENV: production

mongo:
  image: mongo
  volumes:
    - ./storage/mongodb:/data/db

rabbitmq:
  image: rabbitmq
