api-server:
  image: 847166803921.dkr.ecr.us-east-1.amazonaws.com/staff-api-server:latest
  links:
   - mongo
   - rabbitmq
  ports:
   - "80:3000"
  environment:
   MONGO_URI: mongodb://mongo/staffdotcom'
   RABBIT_URI: amqp://rabbitmq
   API_URL: "http://api.staff.local"
   NODE_ENV: production


app-web:
  image: 847166803921.dkr.ecr.us-east-1.amazonaws.com/staff-app-web:latest
  ports:
   - "3000:3000"
  environment:
   API_URL: "http://api.staff.local"
   NODE_ENV: production

mongo:
  image: mongo

rabbitmq:
  image: rabbitmq
